name: 'Update scrum.org classes'
description: 'Update scrum.org classes'
inputs:
    trainer_id:
        description: 'Id of the trainer'
        required: true
    user_agent:
        description: 'User agent to use for the API request'
        required: true
    ghost_token:
        description: 'Ghost API token'
        required: true

runs:
    using: "composite"
    steps:
      - run: $env:GITHUB_ACTION_PATH/update-scrum-classes.ps1 -trainerId $env:trainerId -token $env:token -userAgent $env:userAgent
        shell: pwsh
        env:
            trainerId: ${{ inputs.trainer_id }}
            token: ${{ inputs.ghost_token }}
            userAgent: ${{ inputs.user_agent }}
