name: 'Update scrum.org classes'
description: 'Update scrum.org classes'
inputs:
  trainerId:  
    description: 'Id of the trainer'
    required: true

runs:
  using: "composite"
  steps:
    - script: |
        write-host running
      shell: pwsh
