name: Update Scrum Classes
on:
  schedule: # Run workflow automatically
    - cron: '18 18 * * *' 
  workflow_dispatch:
  
jobs:
  update-readme-with-scrumclasses:
    name: Update GitHub profile
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            www.scrum.org:443

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Update classes on GitHub profile
        uses: jessehouwing/jessehouwing/.github/actions/update-scrum-classes@6df99bbef281985c1ffd6496623d09e082e17481 # main
        with:
          trainer_id: 76
          user_agent: 'JesseHouwingScript'
  update-blog-with-scrumclasses:
    runs-on: ubuntu-latest
    name: Update Ghost Blog
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            scrumbug.ghost.io:443
            www.scrum.org:443

      - name: Update classes on Ghost Blog
        uses: jessehouwing/jessehouwing/.github/actions/update-scrum-classes-on-ghost@6df99bbef281985c1ffd6496623d09e082e17481 # main
        with:
          trainer_id: 76
          user_agent: 'JesseHouwingScript'
          ghost_token: ${{ secrets.GHOST_TOKEN }}
